POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shindrtryredtyerting"
}

###

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
"name": "Serioga",
"avatarUrl": "torrance.png",
"isPro": true,
"email": "torans@overlook.net",
"password": "shindrtryredtyerting"
}

###

## Отправить изображение

POST http://localhost:4000/users/6717e369c934030b401bf05c/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="2150932060.jpg"
Content-Type: image/jpg

< /Users/sergeiragozin/Pictures/Screenshots/2150932060.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
##

###

## Проверить токен пользователя

GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiU2VyaW9nYSIsImF2YXRhclVybCI6InRvcnJhbmNlLnBuZyIsImlzUHJvIjp0cnVlLCJpZCI6IjY3M2NiNGIyM2UxNGY4ODVhZmQxOTNmNiIsImlhdCI6MTczMjAzMTcxOSwiZXhwIjoxNzMyMjA0NTE5fQ.G1nNU5Vfy9V_PMINU2S4Qqb1szITjSegR0WfFWcmOcw

###
