POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
"name": "Serioja",
"avatarUrl": "torrance.png",
"isPro": "true",
"email": "serioja@serioja.ser",
"token": "sdrfgsdrg3456sdg",
"password": "shining"
}

###
