GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

###

POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Very beautiful place",
  "type": "room",
  "price": 2000,
  "city": {
    "name": "Amsterdam",
    "location": {
      "longitude": 33737,
      "latitude": 32867,
      "zoom": 10
    }
  },
  "location": {
    "longitude": 33737,
    "latitude": 32867,
    "zoom": 15
  },
  "isFavorite": true,
  "isPremium": true,
  "rating": 2,
  "description": "shindrtryredtyerting",
  "images": [
    "shindrtryredtyerting",
    "shindrtryredtyerting",
    "shindrtryredtyerting",
    "shindrtryredtyerting",
    "shindrtryredtyerting",
    "shindrtryredtyerting"
  ],
  "previewImage": "shindrtryredtyerting",
  "goods": [
    "Air conditioning",
    "Laptop friendly workspace",
    "Baby seat",
    "Washer"
  ],
  "hostId": "6717e369c934030b401bf05c",
  "bedrooms": 1,
  "maxAdults": 2,
  "commentsCount": 0
}

###

GET http://localhost:4000/offers/6717e369c934030b401bf05e HTTP/1.1
Content-Type: application/json

###

PATCH http://localhost:4000/offers/6717e369c934030b401bf05e HTTP/1.1
Content-Type: application/json

{
  "title": "Vovovfdfjhdfjo"
}

###

DELETE http://localhost:4000/offers/6717e369c934030b401bf05e HTTP/1.1
Content-Type: application/json

###

GET http://localhost:4000/offers/premium HTTP/1.1
Content-Type: application/json

{
  "cityName": "Cologne"
}

###

GET http://localhost:4000/offers/favorites HTTP/1.1
Content-Type: application/json

###

PATCH http://localhost:4000/offers/favorites HTTP/1.1
Content-Type: application/json

{
  "offerId": "670a603ee6a96649c3e38120",
  "favoriteStatus": "true"
}
